// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwobogyydbyggyxyrqfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3b2JvZ3l5ZGJ5Z2d5eHlycWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjYwOTIsImV4cCI6MjA2ODcwMjA5Mn0.ywM5l6qJSyY-7x6ZMKOohTU9N4gZ3qMjgJExYaN4ydU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});